$('form ul li:eq(0),form ul li:eq(2)').css({'width':'406px','padding-left':'16px'});
$('form ul li:eq(1),form ul li:eq(3)').css({'width':'364px'});
$('form ul li').eq(4).css({'height':'92px','width':'768px'});
$('form ul li:eq(4) span').css({'top':'34px'});
$('form ul li').eq(5).css({'width':'380px'});
$('form ul li').eq(6).css({'width':'768px'});
$('form ul li input:eq(1),form ul li input:eq(3)').css({'width':'300px'});
$('form ul li input:eq(4)').css({'width':'696px','height':'92px','margin-left':'70px','line-height':'92px'});
$('form ul li input:eq(5)').css({'height':'48px','margin-left':'70px','width':'302'});
$('form ul li input:eq(6),form ul li input:eq(7)').css({'cursor':'pointer'});
